#!/usr/bin/env bash

printf "%s: " "$0"

function err()
{
    echo "$*"
    exit 1
}

[ "$(../find_ids.py data_target_common_fgij.txt)" == "fgij" ] || err "data_target_common_fgij.txt failed to equal fgij"

echo "SUCCESS"