#!/usr/bin/env bash

printf "%s: " "$0"

function err()
{
    echo "$*"
    exit 1
}

[ "$(../calibrate_repeat data_repeats_10.txt)" == "10" ] || err "data_repeats_10.txt failed to find 10"

[ "$(../calibrate_repeat data_repeats_2_loop_1.txt)" == "2" ] || err "data_repeats_2_loop_1.txt failed to find 2"

[ "$(../calibrate_repeat data_repeats_5_looping.txt)" == "5" ] || err "data_repeats_5_looping.txt failed to find 5"

[ "$(../calibrate_repeat data_repeats_14_looping.txt)" == "14" ] || err "data_repeats_14_looping.txt failed to find 14"

echo "SUCCESS"