#!/usr/bin/env bash

printf "%s: " "$0"

function err()
{
    echo "$*"
    exit 1
}

[ "$(../calibrate data_test_0.txt)" == "0" ] || err "testinput.txt failed to equal zero"

[ "$(../calibrate data_test_0_no_eol.txt)" == "0" ] || err "testinput_no_eol.txt failed to equal zero"

read -r -d '' DATA <<'EOF'
1
2
3
-6
EOF

[ "$(  echo "${DATA}" | ../calibrate )" == "0" ] || err "test stdin failed to equal zero"

echo "SUCCESS"